#---------------------------------------------------------------------------------------------------------------------------------------------
  #Part I:
#---------------------------------------------------------------------------------------------------------------------------------------------
#Generate 200 random values from the standard exponential dist.
#standard exponential distribution has lambda = 1. 
exp.draws.1 = rexp(200)
mean(exp.draws.1)
sd(exp.draws.1)

#Repeat for rates lambda = 0.2, 5, 7.3, 10
exp.draws.0.2 = rexp(200, rate = 0.2)
mean(exp.draws.0.2)
sd(exp.draws.0.2)

exp.draws.5 = rexp(200, rate = 5)
mean(exp.draws.5)
sd(exp.draws.5)

exp.draws.7.3 = rexp(200, rate = 7.3)
mean(exp.draws.7.3)
sd(exp.draws.7.3)

exp.draws.10 = rexp(200, rate = 10)
mean(exp.draws.10)
sd(exp.draws.10)

#Histogram of standard exponential distribution
hist(exp.draws.1)

#Plot values generated by the standard exponential dist. in the order they were generated
plot(exp.draws.1)

#Scatter plot between the standard distribution and the exponential distribution with lambda = 10
plot(exp.draws.1, exp.draws.10)
